src/Entity/Incomes.php
<?php

namespace App\Entity;

use App\Repository\IncomesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=IncomesRepository::class)
 */
class Incomes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=Simulation::class, inversedBy="incomes", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $simulation;

    /**
     * @ORM\Column(type="integer")
     */
    private $bank_loan;

    /**
     * @ORM\Column(type="integer")
     */
    private $personnal_contribution;

    /**
     * @ORM\Column(type="integer")
     */
    private $contribution_in_kind;

    /**
     * @ORM\Column(type="integer")
     */
    private $starting_grant;

    /**
     * @ORM\Column(type="integer")
     */
    private $others_incomes;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSimulation(): ?Simulation
    {
        return $this->simulation;
    }

    public function setSimulation(Simulation $simulation): self
    {
        $this->simulation = $simulation;

        return $this;
    }

    public function getBankLoan(): ?int
    {
        return $this->bank_loan;
    }

    public function setBankLoan(int $bank_loan): self
    {
        $this->bank_loan = $bank_loan;

        return $this;
    }

    public function getPersonnalContribution(): ?int
    {
        return $this->personnal_contribution;
    }

    public function setPersonnalContribution(int $personnal_contribution): self
    {
        $this->personnal_contribution = $personnal_contribution;

        return $this;
    }

    public function getContributionInKind(): ?int
    {
        return $this->contribution_in_kind;
    }

    public function setContributionInKind(int $contribution_in_kind): self
    {
        $this->contribution_in_kind = $contribution_in_kind;

        return $this;
    }

    public function getStartingGrant(): ?int
    {
        return $this->starting_grant;
    }

    public function setStartingGrant(int $starting_grant): self
    {
        $this->starting_grant = $starting_grant;

        return $this;
    }

    public function getOthersIncomes(): ?int
    {
        return $this->others_incomes;
    }

    public function setOthersIncomes(int $others_incomes): self
    {
        $this->others_incomes = $others_incomes;

        return $this;
    }
}

src/Entity/Simulation.php
<?php

namespace App\Entity;

use App\Repository\SimulationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=SimulationRepository::class)
 */
class Simulation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="simulations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("main")
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $state;

    /**
     * @ORM\OneToOne(targetEntity=FirstNeeds::class, mappedBy="simulation", cascade={"persist", "remove"})
     */
    private $firstNeeds;

    /**
     * @ORM\OneToOne(targetEntity=Incomes::class, mappedBy="simulation", cascade={"persist", "remove"})
     */
    private $incomes;

    /**
     * @ORM\OneToOne(targetEntity=Turnover::class, mappedBy="simulation", cascade={"persist", "remove"})
     */
    private $turnover;

    /**
     * @ORM\OneToOne(targetEntity=Costs::class, mappedBy="simulation", cascade={"persist", "remove"})
     */
    private $costs;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getState(): ?bool
    {
        return $this->state;
    }

    public function setState(bool $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getFirstNeeds(): ?FirstNeeds
    {
        return $this->firstNeeds;
    }

    public function setFirstNeeds(FirstNeeds $firstNeeds): self
    {
        $this->firstNeeds = $firstNeeds;

        // set the owning side of the relation if necessary
        if ($firstNeeds->getSimulation() !== $this) {
            $firstNeeds->setSimulation($this);
        }

        return $this;
    }

    public function getIncomes(): ?Incomes
    {
        return $this->incomes;
    }

    public function setIncomes(Incomes $incomes): self
    {
        $this->incomes = $incomes;

        // set the owning side of the relation if necessary
        if ($incomes->getSimulation() !== $this) {
            $incomes->setSimulation($this);
        }

        return $this;
    }

    public function getTurnover(): ?Turnover
    {
        return $this->turnover;
    }

    public function setTurnover(Turnover $turnover): self
    {
        $this->turnover = $turnover;

        // set the owning side of the relation if necessary
        if ($turnover->getSimulation() !== $this) {
            $turnover->setSimulation($this);
        }

        return $this;
    }

    public function getCosts(): ?Costs
    {
        return $this->costs;
    }

    public function setCosts(Costs $costs): self
    {
        $this->costs = $costs;

        // set the owning side of the relation if necessary
        if ($costs->getSimulation() !== $this) {
            $costs->setSimulation($this);
        }

        return $this;
    }
}

src/Controller/SimulationController.php
<?php


namespace App\Controller;


use App\Entity\Costs;
use App\Entity\FirstNeeds;
use App\Entity\Incomes;
use App\Entity\Simulation;
use App\Entity\Turnover;
use App\Form\CostsFormType;
use App\Form\FirstNeedsFormType;
use App\Form\IncomesFormType;
use App\Form\SimulationFormType;
use App\Form\TurnoverFormType;
use App\Repository\SimulationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

class SimulationController extends AbstractController
{
    /**
     * @Route("/new_simulation/{slug?}", name="app_new_simulation")
     */
    public function newSimulation($slug, EntityManagerInterface $em, Request $request)
    {
        // TODO clear session

        if ($slug) {
            $this->editSimulation($slug, $em, $request);
        } else {
            $this->clearSession($request);
        }

        $simulation = new Simulation();

        $form = $this->createForm(SimulationFormType::class, $simulation);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
           // /** @var Simulation $simulation */
            $simulation = $form->getData();
            $session = $request->getSession();
            $session->set('simulation', $simulation);

            //  $this->addFlash();
            return $this->redirectToRoute('app_first_needs', array('slug' => $slug));
        }

        return $this->render('simulation/new_simulation.html.twig', [
            'simulationForm'=>$form->createView(),
        ]);
    }

    /**
     * @Route("/first_needs/{slug?}", name="app_first_needs")
     */
    public function firstNeeds($slug, EntityManagerInterface $em, Request $request, UserInterface $user)
    {
        if ($request->getSession()->has('simulation')) {

            $firstNeeds = new FirstNeeds();

            $form = $this->createForm(FirstNeedsFormType::class, $firstNeeds);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
               // /** @var FirstNeeds $firstNeeds */
                $firstNeeds = $form->getData();
                $session = $request->getSession();
                $session->set('firstNeeds', $firstNeeds);

                // $this->addFlash();
                return $this->redirectToRoute('app_turnover', array('slug' => $slug));
            }
            return $this->render('simulation/first_needs.html.twig', [
                'firstNeedsForm' => $form->createView(),
            ]);
        }
        return $this->redirectToRoute('app_new_simulation'); //TODO Passer slug dans la securité avec session
    }

    /**
     * @Route("/turnover/{slug?}", name="app_turnover")
     */
    public function turnover($slug, EntityManagerInterface $em, Request $request)
    {
        if ($request->getSession()->has('firstNeeds')) {

            $turnover = new Turnover();
            $form = $this->createForm(TurnoverFormType::class, $turnover);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                ///** @var Turnover $turnover */
                $turnover = $form->getData();
                $session = $request->getSession();
                $session->set('turnover', $turnover);

                // $this->addFlash();
                return $this->redirectToRoute('app_incomes', array('slug' => $slug));
            }
            return $this->render('simulation/turnover.html.twig', [
                'turnoverForm' => $form->createView(),
            ]);
        }

        return $this->redirectToRoute('app_new_simulation');
    }

    /**
     * @Route("/incomes/{slug?}", name="app_incomes")
     */
    public function incomes($slug, EntityManagerInterface $em, Request $request)
    {
        if ($request->getSession()->has('turnover')) {

            $incomes = new Incomes();

            $form = $this->createForm(IncomesFormType::class, $incomes);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
               // /** @var Incomes $incomes */
                $incomes = $form->getData();
                $session = $request->getSession();
                $session->set('incomes', $incomes);

                // $this->addFlash();
                return $this->redirectToRoute('app_costs', array('slug' => $slug));
            }
            return $this->render('simulation/incomes.html.twig', [
                'incomesForm' => $form->createView(),
            ]);
        }
        return $this->redirectToRoute('app_new_simulation');
    }

    /**
     * @Route("/costs/{slug?}", name="app_costs")
     */
    public function costs($slug, EntityManagerInterface $em, Request $request)
    {
        if ($request->getSession()->has('incomes')) {

            $costs = new Costs();

            $form = $this->createForm(CostsFormType::class, $costs);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
               // /** @var Costs $costs */
                $costs = $form->getData();
                $session = $request->getSession();
                $session->set('costs', $costs);

                // $this->addFlash();
                return $this->redirectToRoute('app_checking', array('slug' => $slug));
            }
            return $this->render('simulation/costs.html.twig', [
                'costsForm' => $form->createView(),
            ]);
        }
        return $this->redirectToRoute('app_new_simulation');
    }

    /**
     * @Route("/checking/{slug?}", name="app_checking")
     */
    public function checking($slug, Request $request)
    {
        if($request->getSession()->has('costs')) {
            return $this->render('simulation/checking.html.twig', array('slug' => $slug));
        }
        return $this->redirectToRoute('app_new_simulation');
    }

    /**
     * @Route("/flush/{slug?}", name="app_flush")
     */
    public function flush(EntityManagerInterface $em, Request $request)
    {
        if($request->getSession()->has('costs')) {

            $idSimulation = $request->getSession()->get('idSimulation');

            if ($idSimulation == null) {
                $simulation = $request->getSession()->get('simulation');
                $simulation->setUserId($this->getUser());
                $simulation->setCreatedAt(new \DateTime('now'));
                $simulation->setState('1'); // TODO 1 = Valid

                /** @var Simulation $simulation */
                // TODO check if better => /** @var FirstNeeds $firstNeedsSession */
                $firstNeedsSession = $request->getSession()->get('firstNeeds');
                $firstNeedsSession->setSimulation($simulation);

                /** @var Simulation $simulation */
                $turnover = $request->getSession()->get('turnover');
                $turnover->setSimulation($simulation);

                /** @var Simulation $simulation */
                $incomes = $request->getSession()->get('incomes');
                $incomes->setSimulation($simulation);

                /** @var Simulation $simulation */
                $costs = $request->getSession()->get('costs');
                $costs->setSimulation($simulation);

                $em->persist($simulation);
                $em->persist($firstNeedsSession);
                $em->persist($turnover);
                $em->persist($incomes);
                $em->persist($costs);

            } else {
                /** @var Simulation $simulationSession */
                $simulationSession = $request->getSession()->get('simulation');
                /** @var Simulation $simulationBDD */
                $simulationBDD = $em->getRepository(Simulation::class)->find($idSimulation);
                $simulationBDD->setName($simulationSession->getName());

                /** @var FirstNeeds $firstNeedsSession */
                $firstNeedsSession = $request->getSession()->get('firstNeeds');
                /** @var FirstNeeds $firstNeedsBDD */
                $firstNeedsBDD = $em->getRepository(FirstNeeds::class)->findOneBy(['simulation' => $idSimulation]);
                $firstNeedsBDD->setStartingCash($firstNeedsSession->getStartingCash());
                $firstNeedsBDD->setDepreciation($firstNeedsSession->getDepreciation());
                $firstNeedsBDD->setStartingInvestment($firstNeedsSession->getStartingInvestment());
                $firstNeedsBDD->setStartingStock($firstNeedsSession->getStartingStock());
                $firstNeedsBDD->setOthersNeeds($firstNeedsSession->getOthersNeeds());


                /** @var Turnover $turnoverSession */
                $turnoverSession = $request->getSession()->get('turnover');
                /** @var Turnover $turnoverBDD */
                $turnoverBDD = $em->getRepository(Turnover::class)->findOneBy(['simulation' => $idSimulation]);
                $turnoverBDD->setMonthWorked($turnoverSession->getMonthWorked());
                $turnoverBDD->setDaysWorked($turnoverSession->getDaysWorked());
                $turnoverBDD->setDailyRevenue($turnoverSession->getDailyRevenue());
                $turnoverBDD->setTurnoverIncrease($turnoverSession->getTurnoverIncrease());


                /** @var Incomes $incomesSession */
                $incomesSession = $request->getSession()->get('incomes');
                /** @var Incomes $incomesBDD */
                $incomesBDD = $em->getRepository(Incomes::class)->findOneBy(['simulation' => $idSimulation]);
                $incomesBDD->setBankLoan($incomesSession->getBankLoan());
                $incomesBDD->setPersonnalContribution($incomesSession->getPersonnalContribution());
                $incomesBDD->setContributionInKind($incomesSession->getContributionInKind());

templates/simulation/checking.html.twig
{% extends 'base.html.twig' %}

{% block title %} verification {% endblock %}

{% block body %}

    <div class="blockHead headMedium">
        <div class="row title">
            <h1 class="col-12" > Nouvelle Simulation </h1>
        </div>
    </div>

    <div class="row d-flex simulationFormBlock">
        <div class="col-12 ">
            <h2>Vérification des informations</h2>
        </div>
    </div>

    {% set costs = app.session.get('costs') %}
    {% set incomes = app.session.get('incomes') %}

    {{ dump(app.session.get('idSimulation')) }}
    {{ dump(app.session.get('user')) }}
    {{ dump(app.session.get('simulation')) }}
    {{ dump(app.session.get('firstNeeds')) }}
    {{ dump(app.session.get('turnover')) }}
    {{ dump(app.session.get('incomes')) }}
    {{ dump(app.session.get('costs')) }}


    Votre prêt bancaire : {{ incomes.bankLoan }} </br>

                {# Votre CA : {{ incomes.ca }} </br>
                Vos besoin de démarrage : {{ incomes.firstNeeds }} </br>

                {#Vos charges variables : {{ charges.variableCharges }} </br>
                Vos charges fixes : {{ charges.fixedcharge }} </br>#}



    <a class="col-xs-2 center" href="{{ path('app_flush') }}">Valider la simulation</a> </br>
    <a class="col-xs-2 center" href="{{ path('app_first_needs', { slug: slug } ) }}">Modifier les données</a>
{% endblock %}

templates/simulation/costs.html.twig
{% extends 'base.html.twig' %}

{% block title %} charges {% endblock %}

{% block body %}

    <div class="blockHead headMedium">
        <div class="row title">
            <h1 class="col-12" > Nouvelle Simulation </h1>
        </div>
    </div>

    <div class="row d-flex simulationFormBlock">
        <div class="col-12 ">
            <h2>Les charges</h2>
        </div>
    </div>

    {% if app.session.get('costs') is null %}
        {% set salaries = "0" %}
        {% set salariesIncrease = "0" %}
        {% set rent = "0" %}
        {% set insurance = "0" %}
        {% set othersFixedCosts = "0" %}
        {% set variableCosts = "0" %}
        {% set taxes = "0" %}
        {% set corporationTax = "0" %}
    {% else %}
        {% set salaries = app.session.get('costs').salaries %}
        {% set salariesIncrease = app.session.get('costs').salariesIncrease %}
        {% set rent = app.session.get('costs').rent %}
        {% set insurance = app.session.get('costs').insurance %}
        {% set othersFixedCosts = app.session.get('costs').othersFixedCosts %}
        {% set variableCosts = app.session.get('costs').variableCosts %}
        {% set taxes = app.session.get('costs').taxes %}
        {% set corporationTax = app.session.get('costs').corporationTax %}

    {% endif %}

    <div class="row d-flex simulationFormBlock">
        <div class="col-8">

            {{ form_start(costsForm) }}

            {{ form_row(costsForm.salaries, {'value': salaries}) }}
            {{ form_row(costsForm.salaries_increase, {'value': salariesIncrease}) }}
            {{ form_row(costsForm.rent, {'value': rent}) }}
            {{ form_row(costsForm.insurance, {'value': insurance}) }}
            {{ form_row(costsForm.others_fixed_costs, {'value': othersFixedCosts}) }}
            {{ form_row(costsForm.variable_costs, {'value': variableCosts}) }}
            {{ form_row(costsForm.corporation_tax, {'value': corporationTax}) }}
            {{ form_row(costsForm.taxes, {'value': taxes}) }}

            {# {{ form_widget(costsForm) }} #}

            <button type="submit" class="btn btn-primary simulationFormButton">Suivant</button>
            {{ form_end(costsForm) }}

        </div>
    </div>

{% endblock %}

templates/simulation/first_needs.html.twig
{% extends 'base.html.twig' %}

{% block title %} besoins de démarrage {% endblock %}

{% block body %}

    <div class="blockHead headMedium">
        <div class="row title">
            <h1 class="col-12" > Nouvelle Simulation </h1>
        </div>
    </div>

    <div class="row d-flex simulationFormBlock">
        <div class="col-12 ">
            <h2>Mes besoins de démarrage</h2>
        </div>
    </div>

    {% if app.session.get('firstNeeds') is null %}
        {% set startingCash = "0" %}
        {% set startingInvestment = "0" %}
        {% set depreciation = "10" %}
        {% set startingStock = "0" %}
        {% set othersNeeds = "0" %}
    {% else %}
        {% set startingCash = app.session.get('firstNeeds').startingCash %}
        {% set startingInvestment = app.session.get('firstNeeds').startingInvestment %}
        {% set depreciation = app.session.get('firstNeeds').depreciation %}
        {% set startingStock = app.session.get('firstNeeds').startingStock %}
        {% set othersNeeds = app.session.get('firstNeeds').othersNeeds %}
    {% endif %}


    <div class="row d-flex simulationFormBlock">
        <div class="col-8">

            {{ form_start(firstNeedsForm) }}

            {{ form_row(firstNeedsForm.starting_cash, {'value': startingCash}) }}
            {{ form_row(firstNeedsForm.starting_investment, {'value': startingInvestment}) }}
            {{ form_row(firstNeedsForm.depreciation, {'value': depreciation}) }}
            {{ form_row(firstNeedsForm.starting_stock, {'value': startingStock}) }}
            {{ form_row(firstNeedsForm.others_needs, {'value': othersNeeds}) }}

            {#  {{ form_widget(firstNeedsForm) }} #}

            <button type="submit" class="btn btn-primary simulationFormButton">Suivant</button>
            {{ form_end(firstNeedsForm) }}

        </div>
    </div>
{% endblock %}

templates/simulation/incomes.html.twig
{% extends 'base.html.twig' %}

{% block title %} revenues {% endblock %}

{% block body %}

    <div class="blockHead headMedium">
        <div class="row title">
            <h1 class="col-12" > Nouvelle Simulation </h1>
        </div>
    </div>

    <div class="row d-flex simulationFormBlock">
        <div class="col-12 ">
            <h2>Mes revenus</h2>
        </div>
    </div>

    {% if app.session.get('incomes') is null %}
        {% set bankLoan = "0" %}
        {% set personnalContribution = "0" %}
        {% set contributionInKind = "0" %}
        {% set startingGrant = "0" %}
        {% set othersIncomes = "0" %}
    {% else %}
        {% set bankLoan = app.session.get('incomes').bankLoan %}
        {% set personnalContribution = app.session.get('incomes').personnalContribution %}
        {% set contributionInKind = app.session.get('incomes').contributionInKind %}
        {% set startingGrant = app.session.get('incomes').startingGrant %}
        {% set othersIncomes = app.session.get('incomes').othersIncomes %}
    {% endif %}

    <div class="row d-flex simulationFormBlock">
        <div class="col-8">

            {{ form_start(incomesForm) }}

            {{ form_row(incomesForm.bank_loan, {'value': bankLoan}) }}
            {{ form_row(incomesForm.personnal_contribution, {'value': personnalContribution}) }}
            {{ form_row(incomesForm.contribution_in_kind, {'value': contributionInKind}) }}
            {{ form_row(incomesForm.starting_grant, {'value': startingGrant}) }}
            {{ form_row(incomesForm.others_incomes, {'value': othersIncomes}) }}

            {# {{ form_widget(incomesForm) }} #}

            <button type="submit" class="btn btn-primary simulationFormButton">Suivant</button>
            {{ form_end(incomesForm) }}
        </div>
    </div>

{% endblock %}

templates/simulation/new_simulation.html.twig
{% extends 'base.html.twig' %}

{% block title %} nouvelle simulation {% endblock %}

{% block body %}

    <div class="blockHead headMedium">
        <div class="row title">
            <h1 class="col-12" > Nouvelle Simulation </h1>
        </div>
    </div>

    <div class="row d-flex simulationFormBlock">
        <div class="col-12 ">
            <h2>Commencer la simulation</h2>
        </div>
    </div>

    {% if app.session.get('simulation') is null %}
        {% set simulationName = "Nouvelle simulation" %}
    {% else %}
        {% set simulationName = app.session.get('simulation').name %}
    {% endif %}

    <div class="row d-flex simulationFormBlock">
        <div class="col-8">
            {{ form_start(simulationForm) }}

            {# {{ form_label(simulationForm.name, 'Nom de la simulation test') }} #}

            {{ form_row(simulationForm.name, {'value': simulationName}) }}

            {# {{ form_widget(simulationForm.name) }} #}

            {# <small>{{ form_help(simulationForm.name) }}</small> #}

            <button type="submit" class="btn btn-primary simulationFormButton">Valider</button>
            {{ form_end(simulationForm) }}
        </div>
    </div>

{% endblock %}

templates/simulation/turnover.html.twig
{% extends 'base.html.twig' %}

{% block title %} chiffre d'affaire {% endblock %}

{% block body %}

    <div class="blockHead headMedium">
        <div class="row title">
            <h1 class="col-12" > Nouvelle Simulation </h1>
        </div>
    </div>

    <div class="row d-flex simulationFormBlock">
        <div class="col-12 ">
            <h2>Mon chiffre d'affaire</h2>
        </div>
    </div>

    {{ dump(app.session.get('turnover')) }}
    {{ dump(app.session.get('incomes')) }}

    {% if app.session.get('turnover') is null %}
        {% set monthWorked = "12" %}
        {% set daysWorked = "30" %}
        {% set dailyRevenue = "0" %}
        {% set turnoverIncrease = "0" %}
    {% else %}
        {% set monthWorked = app.session.get('turnover').monthWorked %}
        {% set daysWorked = app.session.get('turnover').daysWorked %}
        {% set dailyRevenue = app.session.get('turnover').dailyRevenue %}
        {% set turnoverIncrease = app.session.get('turnover').turnoverIncrease %}
    {% endif %}

    <div class="row d-flex simulationFormBlock">
        <div class="col-8">
            {{ form_start(turnoverForm) }}

            {{ form_row(turnoverForm.month_worked, {'value': monthWorked}) }}
            {{ form_row(turnoverForm.days_worked, {'value': daysWorked}) }}
            {{ form_row(turnoverForm.daily_revenue, {'value': dailyRevenue}) }}
            {{ form_row(turnoverForm.turnover_increase, {'value': turnoverIncrease}) }}

            {#  {{ form_widget(turnoverForm) }} #}


            <button type="submit" class="btn btn-primary simulationFormButton">Suivant</button>
            {{ form_end(turnoverForm) }}
        </div>
    </div>
{% endblock %}