src/Entity/Simulation.php
<?php

namespace App\Entity;

use App\Repository\SimulationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=SimulationRepository::class)
 */
class Simulation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="simulations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("main")
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $state;

    /**
     * @ORM\OneToOne(targetEntity=FirstNeeds::class, mappedBy="simulation", cascade={"persist", "remove"})
     */
    private $firstNeeds;

    /**
     * @ORM\OneToOne(targetEntity=Incomes::class, mappedBy="simulation", cascade={"persist", "remove"})
     */
    private $incomes;

    /**
     * @ORM\OneToOne(targetEntity=Turnover::class, mappedBy="simulation", cascade={"persist", "remove"})
     */
    private $turnover;

    /**
     * @ORM\OneToOne(targetEntity=Costs::class, mappedBy="simulation", cascade={"persist", "remove"})
     */
    private $costs;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getState(): ?bool
    {
        return $this->state;
    }

    public function setState(bool $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getFirstNeeds(): ?FirstNeeds
    {
        return $this->firstNeeds;
    }

    public function setFirstNeeds(FirstNeeds $firstNeeds): self
    {
        $this->firstNeeds = $firstNeeds;

        // set the owning side of the relation if necessary
        if ($firstNeeds->getSimulation() !== $this) {
            $firstNeeds->setSimulation($this);
        }

        return $this;
    }

    public function getIncomes(): ?Incomes
    {
        return $this->incomes;
    }

    public function setIncomes(Incomes $incomes): self
    {
        $this->incomes = $incomes;

        // set the owning side of the relation if necessary
        if ($incomes->getSimulation() !== $this) {
            $incomes->setSimulation($this);
        }

        return $this;
    }

    public function getTurnover(): ?Turnover
    {
        return $this->turnover;
    }

    public function setTurnover(Turnover $turnover): self
    {
        $this->turnover = $turnover;

        // set the owning side of the relation if necessary
        if ($turnover->getSimulation() !== $this) {
            $turnover->setSimulation($this);
        }

        return $this;
    }

    public function getCosts(): ?Costs
    {
        return $this->costs;
    }

    public function setCosts(Costs $costs): self
    {
        $this->costs = $costs;

        // set the owning side of the relation if necessary
        if ($costs->getSimulation() !== $this) {
            $costs->setSimulation($this);
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity=Simulation::class, mappedBy="user_id")
     */
    private $simulations;

    public function __construct()
    {
        $this->simulations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Simulation[]
     */
    public function getSimulations(): Collection
    {
        return $this->simulations;
    }

    public function addSimulation(Simulation $simulation): self
    {
        if (!$this->simulations->contains($simulation)) {
            $this->simulations[] = $simulation;
            $simulation->setUserId($this);
        }

        return $this;
    }

    public function removeSimulation(Simulation $simulation): self
    {
        if ($this->simulations->contains($simulation)) {
            $this->simulations->removeElement($simulation);
            // set the owning side to null (unless already changed)
            if ($simulation->getUserId() === $this) {
                $simulation->setUserId(null);
            }
        }

        return $this;
    }
}

templates/author.html.twig
{% extends 'base.html.twig' %}

{% block title %} Author {% endblock %}

{% block body %}
    <div class="blockHead">
        <div class="row title">
            <h1 class="col-12" > L'auteur </h1>
        </div>

        {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
            <div class="row d-flex justify-content-center homepageButton">
                <a class="col-5 col-sm-3 col-lg-2 center" href="{{ path('app_register') }}"> S'enregistrer </a>
                <a class="col-5 col-sm-3 col-lg-2 center" href="{{ path('app_login') }}"> Se connecter </a>
            </div>
        {% endif %}
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <div class="row d-flex justify-content-center homepageButton">
                <a class="col-5 col-sm-3 col-lg-2 center" href="{{ path('app_dashboard') }}"> Tableau de bord </a>
                <a class="col-5 col-sm-3 col-lg-2 center" href="{{ path('app_logout') }}"> Se déconnecter </a>
            </div>
        {% endif %}

    </div>

    <div class="row planningSteps">
        <div class="col-12">
            <div class="row">
                <h2 class="col-12">Pourquoi planifier ?</h2>
            </div>
            <div class="row">
                <p class="col-12">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet leo nunc. Aenean vel libero id augue rhoncus convallis. Maecenas tempus interdum fermentum. </p>
            </div>
        </div>
    </div>

    <div class="row planningFact">
        <div class="col-5">Image</div>
        <div class="col-7">
            <p class="planningData">2351</p>
            <p>Lorem ipsum dolor sit amet.</p>
        </div>
    </div>

    <div class="row planningSteps">
        <div class="col-12">
            <div class="row">
                <h2 class="col-12">Comment planifier ?</h2>
            </div>
            <div class="row">
                <p class="col-12">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet leo nunc. Aenean vel libero id augue rhoncus convallis. Maecenas tempus interdum fermentum. </p>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            {# <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

            <link href="{{ asset('bootstrap/bootstrap.css') }}" rel="stylesheet">
            #}

            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
            <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        {% endblock %}
    </head>
    <body class="container">

        <header class="row no-gutters">
            <div class="col-12">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand" href="{{ path('app_homepage') }}"> <img class="logo" src="{{ asset('images/bluespoon.png') }}" alt="Logo"> </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="{{ path('app_homepage') }}">Accueil<span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_explanation') }}">L'application</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_author') }}">L'auteur</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_contact') }}">Contact</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Mon Compte</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
                                        <a class="dropdown-item" href="{{ path('app_register') }}">S'enregistrer</a>
                                        <a class="dropdown-item"  href="{{ path('app_login') }}">Se connecter</a>
                                    {% endif %}
                                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                                        <a class="nav-link" href="{{ path('app_dashboard') }}">Tableau de bord</a>
                                        <a class="nav-link" href="{{ path('app_profile') }}">Mon profil</a>
                                        <a class="nav-link" href="{{ path('app_logout') }}">Se déconnecter</a>
                                    {% endif %}
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </header>

        {% block body %}{% endblock %}

        <footer class="row no-gutters">
            <p class="col-12 align-self-center">Site réalisé dans le cadre d'une formation OpenClassrooms</p>
        </footer>


        {% block javascripts %}


            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

            <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.3/jspdf.debug.js"></script>

        {% endblock %}
    </body>
</html>

templates/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %} Contact {% endblock %}

{% block body %}

    <div class="blockHead headLarge">
        <div class="row title">
            <h1 class="col-12"> Me Contacter </h1>
        </div>
    </div>

    <div class="blueBackground">
        <div class="blockDashboard profileDashboard">
            <div class="row">
                <p class="col-12 textContact"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. In faucibus, augue maximus eleifend interdum, felis nisi tincidunt erat, non facilisis nisl tellus eu ipsum. Integer quis dolor risus. Nunc accumsan, lectus ac sollicitudin faucibus, diam diam condimentum eros, vel gravida elit odio ornare libero. Suspendisse rutrum est sed vehicula laoreet. Aenean elementum sit amet nisl vel iaculis. Pellentesque convallis ultricies molestie. Sed vitae tempus nisl.  </p>
            </div>
            <div class="contactDetails">
                <div class="row no-gutters">
                    <a href="tel:0033102030405" class="col-12 ">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                            <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
                        </svg>
                        +33 (0)1 02 03 04 05
                    </a>
                </div>
                <div class="row no-gutters contactMail">
                    <a href="mailto:name@rapidtables.com?subject=Demande%20de%20contact%20Blue%20Spoon" class="col-12">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
                            <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z"/>
                        </svg>
                        bluespoonsimulation@gmail.com
                    </a>
                </div>
            </div>

        </div>

    </div>


{% endblock %}

templates/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %} Profil {% endblock %}

{% block body %}

    <div class="blockHead headLarge">
        <div class="row title">
            <h1 class="col-12"> Mon Profil </h1>
        </div>
    </div>

    <div class="blueBackground">
        <div class="blockDashboard profileDashboard">
            <div class="row no-gutters backLink">
                <div class="col-6">
                    <a href="{{ path('app_dashboard')}}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-short" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
                        </svg>
                        Tableau de bord
                    </a>
                </div>
            </div>
            
            <div class="row no-gutters profileTable">
                <div class="col align-self-center">
                    <div class="row d-flex justify-content-center no-gutters">
                        <table class="table border-primary table-hover">
                            <tbody>
                            <tr class="d-flex">
                                <th scope="row" class="col-4">Mon Nom</th>
                                <td class="col-4">{{app.user.name}}</td>
                                <td class="col-4">
                                    <a href="{{ path('app_simulations_list')}}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                        </svg>
                                        Modifier
                                    </a>
                                </td>
                            </tr>
                            <tr class="d-flex">
                                <th scope="row" class="col-4">Mon E-mail</th>
                                <td class="col-4">{{ app.user.username }}</td>
                                <td class="col-4">
                                    <a href="{{ path('app_simulations_list')}}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                        </svg>
                                        Modifier
                                    </a>
                                </td>
                            </tr>
                            <tr class="d-flex">
                                <th scope="row" class="col-4">Mon Mot de Passe</th>
                                <td class="col-4">*****</td>
                                <td class="col-4">
                                    <a href="{{ path('app_simulations_list')}}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                        </svg>
                                        Modifier
                                    </a>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>


{% endblock %}

templates/simulations_draft.html.twig
{% extends 'base.html.twig' %}

{% block title %} All drafts {% endblock %}

{% block body %}

    <p>Mes Brouillons</p>

    {% for simulation in simulations %}
        <a> Reprendre {{ simulation.name }}
            sauvegardée le {{ simulation.createdAt|format_datetime(locale='fr') }}</a></br>
    {% endfor %}

{% endblock %}

templates/simulations_list.html.twig
{% extends 'base.html.twig' %}

{% block title %} All simulations {% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/algolia-autocomplete.css') }}">
{% endblock %}

{% block body %}

    <div class="blockHead headLarge">
        <div class="row title">
            <h1 class="col-12" > Mes Simulations </h1>
        </div>
    </div>

    <div class="blueBackground">

{#TODO class to rename + check bootstrap margin#}

        <div class="blockDashboard">
            <div class="row no-gutters backLink">
                <div class="col-6">
                    <a href="{{ path('app_dashboard')}}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-short" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
                        </svg>
                        Tableau de bord
                    </a>
                </div>
                <div class="col-6 d-flex justify-content-end">
                    <a href="{{ path('app_simulations_list')}}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-counterclockwise" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M8 3a5 5 0 1 1-4.546 2.914.5.5 0 0 0-.908-.417A6 6 0 1 0 8 2v1z"/>
                            <path d="M8 4.466V.534a.25.25 0 0 0-.41-.192L5.23 2.308a.25.25 0 0 0 0 .384l2.36 1.966A.25.25 0 0 0 8 4.466z"/>
                        </svg>
                        Réinitialiser la recherche
                    </a>
                </div>
            </div>


            <div class="row justify-content-center no-gutters">
                <div class="col-8 searchForm">
                    {{ form_start(simulationForm) }}

                    {{ form_row(simulationForm.name, {
                        attr: {placeholder: 'Recherchez une simulation' }
                    }) }}

                    <button type="submit" class="btn btn-primary">Chercher</button>

                    {{ form_end(simulationForm) }}
                </div>
            </div>

            <div class="row no-gutters align-items-center justify-content-around">
                {% if (simulations|length == 0) %}
                    <div class="col-12">
                        Aucune simulation trouvée
                    </div>
                {% endif %}
                {% for simulation in simulations %}
                    <div class="col-5">
                        <div class="simulationListLink" >
                            <a href="{{ path('app_simulation_view', { slug: simulation.id }) }}">{{ simulation.name }} </br> créée le {{ simulation.createdAt|format_datetime(locale='fr') }}</a></br>
                        </div>
                    </div>
                    <div class="col-5 d-flex justify-content-start">
                        <div class="simulationListLink" >
                            <a href="{{ path('app_simulation_view', { slug: simulation.id }) }}">
                                Voir
                                <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
                                </svg>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>


{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.jquery.min.js"></script>
    <script src="{{ asset('js/algolia-autocomplete.js') }}"></script>
{% endblock %}